name: Build WorkFlow
on: 
  # push: 
  #   branches:
  #     - main

  # pull_request: 
  #   branches:
  #     - main 
  
  workflow_dispatch:

  #schedule:
  #  - cron: "30 13 * * 1-5"
env:
  ECR_REPOSITORY: 'webtest-images'

permissions:
  contents: read

jobs: 
  Build: 
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Maven Build
        run: mvn install

      - name: Upload Build Artifact (WAR)
        uses: actions/upload-artifact@v4
        with:
          name: vprofile-app
          path: target/*.war

      - name: Notify if Build Fails
        if: failure()
        run: echo "Build job failed! Please check logs."

  Testing:
    runs-on: ubuntu-latest
    needs: Build
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run tests on main branch
        if: github.ref == 'refs/heads/main'
        run: mvn test

      - name: Checkstyle
        if: github.ref == 'refs/heads/main'
        run: mvn checkstyle:checkstyle

      - name: Run tests on other branches
        if: github.ref != 'refs/heads/main'
        run: echo "Skipping unit tests and code analysis"


  # Security_scan:
  #   runs-on: ubuntu-latest
  #   needs: Build
  #   steps:
  #     - name: Download Build Artifact
  #       uses: actions/download-artifact@v4
  #       with:
  #         name: vprofile-app  
  #         path: .                      

  #     - name: Install Trivy Tool
  #       uses: aquasecurity/setup-trivy@v0.2.2
  #       env:
  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #       with:
  #         cache: false

  #     - name: Scan Artifact (.war file)
  #       run: |
  #         trivy fs *.war \
  #           --format json \
  #           --output trivy-result.json \
  #           --severity CRITICAL,HIGH \
  #           --scanners vuln \
  #           --exit-code 0

  #     - name: Upload Trivy JSON Report
  #       uses: actions/upload-artifact@v4
  #       with:
  #         name: trivy-security-report
  #         path: trivy-result.json      
  #         retention-days: 5            

  # Build_and_publish:
  #   name: Build_and_publish
  #   runs-on: ubuntu-latest
  #   environment: action
  #   needs: [Build, Testing, Security_scan]
  #   if: github.ref == 'refs/heads/main'
  #   steps:
  #     - name: Code checkout
  #       uses: actions/checkout@v4
  #       with:
  #         fetch-depth: 0

  #     - name: Configure AWS credentials
  #       uses: aws-actions/configure-aws-credentials@v1
  #       with:
  #         aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
  #         aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  #         aws-region: ${{ vars.AWS_REGION }}
      
  #     - name: Login to Amazon ECR
  #       id: login-ecr 
  #       uses: aws-actions/amazon-ecr-login@v2

  #     - name: Build, tag, and push image to Amazon ECR
  #       id: build-image
  #       env:
  #         ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
  #         IMAGE_TAG: ${{ github.sha }}
  #       run: |
  #         docker build -f Docker-files/app/multistage/Dockerfile -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
  #         docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
  # Security_scan:
  #   runs-on: ubuntu-latest
  #   needs: Build
  #   # [QUAN TRỌNG] Cấp quyền cho workflow đẩy cảnh báo lên tab Security của GitHub
  #   permissions:
  #     contents: read
  #     security-events: write 
      
  #   steps:
  #     - name: Download Build Artifact
  #       uses: actions/download-artifact@v4
  #       with:
  #         name: vprofile-app
  #         path: .

  #     - name: Install Trivy Tool
  #       uses: aquasecurity/setup-trivy@v0.2.2
  #       with:
  #         cache: true
  #       #  version: v0.58.2

  #     # BƯỚC 3: Quét và xuất ra định dạng SARIF (Chuẩn của GitHub)
  #     - name: Scan Artifact and generate SARIF
  #       run: |
  #         trivy fs *.war \
  #           --format sarif \
  #           --output trivy-results.sarif \
  #           --severity CRITICAL,HIGH \
  #           --scanners vuln \
  #           --exit-code 0

  #     # BƯỚC 4: Đẩy file SARIF lên hệ thống Security của GitHub
  #     - name: Upload SARIF to GitHub Security tab
  #       uses: github/codeql-action/upload-sarif@v3
  #       with:
  #         sarif_file: 'trivy-results.sarif'
  #         category: 'trivy-artifact-scan'
        